# [Preface]{style="color: #004b23"} {.unnumbered}

Social psychology is built on a strong set of classical research paradigms and findings, featured in many of the textbooks, syllabi, online courses and teacRima-hing guides that aspiring psychologists study with and established psychologists use as teaching resources. However, the common body of knowledge that social psychology relies on is undergoing change. Modern research methods and changing attitudes towards permissible research practices bring about social psychological research that looks different today than it used. This book is dedicated to tracing some of these changes, and to offering a version of record of the changing perceptions and interpretations of classic social psychology in the light of it's contemporary counterpart. As such, this study book is a snapshot of how we see social psychology today.

Because it tends to be difficult to keep teaching and study materials up to date with emerging trends and debates, we see this study book as an addition to traditional educational resources in social psychology. It is published as an Open Educational Resource to aid the accessibility of this knowledge for all, and to be adapted to teachers' and learners' needs as they dive into what social psychology has to offer.
